---
title: "Analyse des données avec Phyloseq"
author : Mélody Lebrun
date: "3 janvier 2022"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Préparation de l'environnement

```{r}
library(phyloseq)
library(ggplot2)
library(readr)

```

```{r}
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
```

```{r}
load("02_Data-analysis-with-DADA2_FinalEnv")
```

# Construire un arbre phylogénétique permettant de relié les variants de séquences

```{r}
seqs <- getSequences(seqtabNoC)
names(seqs) <- seqs 
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA,verbose=FALSE)
```

```{r}
phangAlign <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phangAlign)
treeNJ <- NJ(dm)
fit = pml(treeNJ, data=phangAlign)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
        rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)
```

#### PB a résoudre PS EXCEL #### 
# Combiner des données dans un objet phyloseq

```{r}
Metadonnees<-read.csv(file="SraRunTable(2).txt")
Metadonnees<-read.table("SraRunTable(2).txt", header=TRUE, sep=",")
Metadonnees$SampleID <- paste0(gsub("00", "", Metadonnees$host_subject_id), "D", Metadonnees$age-21)
Metadonnees <- Metadonnees[!duplicated(Metadonnees$SampleID),]
rownames(seqtabAll) <- gsub("124", "125", rownames(seqtabAll)) # Fix discrepancy
all(rownames(seqtabAll) %in% Metadonnees$SampleID)
```

```{r}
rownames(Metadonnees) <- Metadonnees$SampleID
keep.cols <- c("Run", "Assay.type", "AvgSpotLen", "Bases",
"BioProject", "BioSample", "BioSample", "BioSampleModel", "Bytes", "Center.Name",
"Collection_Data", "Consent", "DATASTORE.provider", "DATASTORE.region", "env_broad_scale", "env_local_scale", "env_medium", "Experiment", "geo_loc_name_country", "geo_loc_name_country_continent", "geo_loc_name", "host_length", "Host", "host_taxid", "host_issue_sampled", "Instrument", "Isolation_source", "lat_lon", "Library.Name","LibraryLayout", "LibrarySelection", "LibrarySource", "Organism", "Plattform", "ReleaseDate", "Sample.Name", "SRA.Study", "SampleID") 
Metadonnees <- Metadonnees[rownames(seqtabAll), keep.cols]
```

# ici pb non réglé
```{r}
library(phyloseq)
ps <- phyloseq(otu_table(seqtabNoC, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxTab),phy_tree(fitGTR$tree))
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample
ps
```

## Utilisation de phyloseq

```{r}
rank_names(ps) #rang de la base de donnée
table(tax_table(ps)[, "Phylum"], exclude = NULL) # creation d'une table montrant les phylums avec une caractéristique observée
```

```{r}
ps <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized")) # supression des phylums non caractérisés
```

```{r}
prevdf = apply(X = otu_table(ps),
               MARGIN = ifelse(taxa_are_rows(ps), yes = 1, no = 2),
               FUN = function(x){sum(x > 0)})

prevdf = data.frame(Prevalence = prevdf,
                    TotalAbundance = taxa_sums(ps),
                    tax_table(ps))
# prévalence des caractéristiques dans l'ensemble des données cad le nb de fois que le taxon apparait dans l'échantillon
```

```{r}
plyr::ddply(prevdf, "Phylum", function(df1){cbind(mean(df1$Prevalence),sum(df1$Prevalence))})
# calcule des prévalences totales et moyennes des caractéristiques dans chaque embranchement
```

```{r}
filterPhyla = c("Fusobacteria", "Deinococcus-Thermus")
# Filtrations "supervisées" des phylums dans la base de donnée de référence taxonomique
ps1 = subset_taxa(ps, !Phylum %in% filterPhyla)
ps1
```

# Filtration "non supervisées" reposant sur les données de l'article
```{r}
#lien entre la prévalence et le nombre total de lectures pour chaque caractéristique.

prevdf1 = subset(prevdf, Phylum %in% get_taxa_unique(ps1, "Phylum"))
ggplot(prevdf1, aes(TotalAbundance, Prevalence / nsamples(ps),color=Phylum)) +

  geom_hline(yintercept = 0.05, alpha = 0.5, linetype = 2) +  geom_point(size = 2, alpha = 0.7) +
  scale_x_log10() +  xlab("Total Abundance") + ylab("Prevalence [Frac. Samples]") +
  facet_wrap(~Phylum) + theme(legend.position="none")
```
 
```{r}
# Le seuil de prévalence est définie à 5% pour l'ensemble des échantillons
prevalenceThreshold = 0.05 * nsamples(ps)
prevalenceThreshold
```

```{r}
keepTaxa = rownames(prevdf1)[(prevdf1$Prevalence >= prevalenceThreshold)]
ps2 = prune_taxa(keepTaxa, ps)
```

```{r}

```

```{r}

```